//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Exception {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Delivery.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UNKOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKOWN_ERROR", resourceCulture);
            }
        }
        
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        public static string CPF_REQUIRED {
            get {
                return ResourceManager.GetString("CPF_REQUIRED", resourceCulture);
            }
        }
        
        public static string DELIVERYMAN_NOT_FOUND {
            get {
                return ResourceManager.GetString("DELIVERYMAN_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string INVALID_DATE_OF_BIRTH {
            get {
                return ResourceManager.GetString("INVALID_DATE_OF_BIRTH", resourceCulture);
            }
        }
        
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string USERNAME_REQUIRED {
            get {
                return ResourceManager.GetString("USERNAME_REQUIRED", resourceCulture);
            }
        }
        
        public static string ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("ROLE_REQUIRED", resourceCulture);
            }
        }
        
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("USERNAME_EXISTS", resourceCulture);
            }
        }
        
        public static string UNHAUTORIZED_ERROR {
            get {
                return ResourceManager.GetString("UNHAUTORIZED_ERROR", resourceCulture);
            }
        }
        public static string DURATION_MAX_LIMIT {
            get {
                return ResourceManager.GetString("DURATION_MAX_LIMIT", resourceCulture);
            }
        }
        public static string URLVIDEO_REQUIRED {
            get {
                return ResourceManager.GetString("URLVIDEO_REQUIRED", resourceCulture);
            }
        }
        public static string THUMB_REQUIRED {
            get {
                return ResourceManager.GetString("THUMB_REQUIRED", resourceCulture);
            }
        }
        public static string TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }
        public static string FEED_NOT_FOUND {
            get {
                return ResourceManager.GetString("FEED_NOT_FOUND", resourceCulture);
            }
        }
                public static string CODE_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_REQUIRED", resourceCulture);
            }
        }
                public static string UNIT_MEASURE_REQUIRED {
            get {
                return ResourceManager.GetString("UNIT_MEASURE_REQUIRED", resourceCulture);
            }
        }
                public static string DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
    }
}
